# Generated by Django 5.0.1 on 2024-01-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_news_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='archived',
        ),
    ]
